import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import LoadingProgress from "@/components/LoadingProgress";
import Main from "@/components/Main";
import ProgressBar from "@/components/ProgressBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Fit Buddy",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} light`}>
				<ProgressBar progress={10} />
				<LoadingProgress />
				<Navbar />
				<Main>{children}</Main>
			</body>
		</html>
	);
}
